auto_marker_docking_node:
  ros__parameters:
    camera_topic: "/camera/color/image_raw"
    cmd_vel_topic: "/mirte_base_controller/cmd_vel"
    aruco_dict_id: 10           # 6x6_250
    marker_size: 0.10           # meters

    camera_matrix: [1455.23240, 0.0, 933.151651,
                    0.0, 1452.69605, 528.910265,
                    0.0, 0.0, 1.0]   #For Orbbec Astra Pro Plus camera used on Mirte Master must be changed when used with other camera

    dist_coeffs: [0.18919004, -0.65017582,  0.00117596, -0.00382426,  0.78511447] #For Orbbec Astra Pro Plus camera used on Mirte Master must be changed when used with other camera

    drive_speed: 0.3
    stop_distance: 0.50
    min_step: 0.10
    turn_speed: 0.4
    yaw_gain: 1.0
    yaw_turn_threshold: 0.09
    marker_timeout: 1.0
    lost_threshold: 5
